import WorkingWithGradient.add_diagonal_gradient_ps
import WorkingWithGradient.add_diagonal_gradient_xps
import WorkingWithGradient.add_horizontal_gradient_ps
import WorkingWithGradient.add_horizontal_gradient_xps
import WorkingWithGradient.add_radial_gradient_1ps
import WorkingWithGradient.add_radial_gradient_2ps
import WorkingWithGradient.add_vertical_gradient_ps
import WorkingWithGradient.add_vertical_gradient_xps
